[package]
name = "binary_tree"
version = "0.1.0"
authors = ["Alisson Claudino <alisson.claudino@azion.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 0
debug = true

[dependencies]
rand = "0.8"
